name: "Prepare MU Plugins"
description: ""
inputs:
  path:
    description: "Where dependencies should be copied to"
    required: true
  git-token:
    description: "GIT Token to use when checking out and commiting"
    required: true
  mu-repo:
    description: "The MU Plugins repo"
    required: false
    default: "saucal/saucal-mu-plugins-built"
  mu-branch:
    description: "The MU Plugins repo branch"
    required: false
    default: "main"
  add-mu-plugins:
    description: "Whether or not to add our MU-Plugins"
    required: false
    default: "auto"

runs:
  using: "composite"
  steps:
    - name: Check if we need MU-Plugins
      id: vars
      shell: bash
      run: |
        if [ "${{ inputs.add-mu-plugins }}" == "auto" ]; then
          if [ -d "${{ inputs.path }}/client-mu-plugins" ] && [ ! -d "${{ inputs.path }}/vip-config" ]; then
            echo "do_add=true" >> $GITHUB_OUTPUT
          else
            echo "do_add=false" >> $GITHUB_OUTPUT
          fi
        else
          echo "do_add=${{ inputs.add-mu-plugins }}" >> $GITHUB_OUTPUT
        fi

    - name: Add MU Plugins
      if: ${{ steps.vars.outputs.do_add == 'true' }}
      uses: saucal/action-checkout-extended@v2
      with: 
        token: ${{ inputs.git-token }}
        path: "${{ inputs.path }}/mu-plugins"
        repo: ${{ inputs.mu-repo }}
        use: ${{ inputs.mu-branch }}

    - name: Cleanup GIT files from MU Plugins directory
      if: ${{ steps.vars.outputs.do_add == 'true' }}
      shell: bash
      run: rm -rf "${{ inputs.path }}/mu-plugins/.git"

